import { useMemo, useState } from 'react';
import type { AuditReport, FixtureContent } from '../types';

interface Props {
  report: AuditReport;
  fixture: FixtureContent;
}

/**
 * Auto-generated, honestly-worded conformance statement. Deliberately labeled
 * as a self-assessment illustration, it never claims a certified audit or full
 * legal compliance.
 */
function buildStatement(report: AuditReport, fixture: FixtureContent): string {
  const date = new Date(report.ranAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const { passCount, failCount, warnCount, checks } = report;

  const standards = 'WCAG 2.2 Level AA success criteria and the W3C ARIA Authoring Practices Dialog (Modal) pattern';

  if (failCount === 0 && warnCount === 0) {
    return [
      `Accessibility statement for the “${fixture.name}” popup`,
      ``,
      `Self-assessment as of ${date}.`,
      ``,
      `This popup has been evaluated against ${standards}. All ${passCount} automated and interactive checks in this assessment passed, including color contrast, form-field labeling, text alternatives, modal dialog semantics, keyboard focus containment, Escape-to-close, focus return, and a visible focus indicator.`,
      ``,
      `On the criteria tested, the popup conforms to WCAG 2.2 AA. We are committed to keeping it accessible and welcome feedback at accessibility@yourstore.example.`,
      ``,
      `Note: This is a self-assessment illustration generated by Alia Access Guardrail, not a certified third-party audit or a legal determination of ADA / EAA compliance. Automated tooling cannot detect every barrier; a manual review with assistive-technology users is recommended before relying on this statement.`,
    ].join('\n');
  }

  const failed = checks
    .filter((c) => c.status === 'fail')
    .map((c) => `${c.title} (${c.citation.label})`);

  return [
    `Accessibility statement for the “${fixture.name}” popup`,
    ``,
    `Self-assessment as of ${date}.`,
    ``,
    `This popup has been evaluated against ${standards}. ${passCount} of ${checks.length} checks currently pass. The following known barriers were detected and are not yet resolved:`,
    ``,
    ...failed.map((f) => `  • ${f}`),
    ``,
    `Until these are addressed, this popup does not conform to WCAG 2.2 AA and may present barriers to keyboard and screen-reader users. Remediation is in progress.`,
    ``,
    `Note: This is a self-assessment illustration generated by Alia Access Guardrail, not a certified third-party audit or a legal determination of ADA / EAA compliance.`,
  ].join('\n');
}

export default function AccessibilityStatement({ report, fixture }: Props) {
  const [copied, setCopied] = useState(false);
  const statement = useMemo(() => buildStatement(report, fixture), [report, fixture]);

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(statement);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  };

  const conformant = report.failCount === 0 && report.warnCount === 0;

  return (
    <section
      className="rounded-alia border border-alia-border bg-alia-surface p-5 shadow-alia-card"
      aria-labelledby="statement-heading"
    >
      <div className="flex items-center justify-between gap-3">
        <h2 id="statement-heading" className="text-sm font-bold text-alia-ink">
          Auto-generated accessibility statement
        </h2>
        <button
          type="button"
          onClick={onCopy}
          className="shrink-0 rounded-alia-sm border border-alia-border-strong bg-alia-surface px-3 py-1.5 text-xs font-semibold text-alia-ink transition hover:bg-alia-surface-2"
        >
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>

      <span
        className={`mt-2 inline-block rounded-full px-2.5 py-0.5 text-[11px] font-semibold ${
          conformant ? 'bg-alia-pass-bg text-alia-pass' : 'bg-alia-warn-bg text-alia-warn'
        }`}
      >
        {conformant ? 'Draft: conforms on tested criteria' : 'Draft: known barriers disclosed'}
      </span>

      <pre className="mt-3 max-h-64 overflow-auto whitespace-pre-wrap rounded-alia-sm bg-alia-surface-2 p-3.5 font-mono text-[12px] leading-relaxed text-alia-ink-soft">
        {statement}
      </pre>
      <p className="mt-2 text-[11px] text-alia-ink-muted">
        Illustration only. Not a certified audit or a legal compliance determination.
      </p>
    </section>
  );
}
